# Generated by Django 4.0.5 on 2022-06-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_username"),
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="autor_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="users.autor"
            ),
        ),
    ]
