# Generated by Django 4.0.5 on 2022-06-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag_autor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="autor_id",
        ),
    ]
