# Generated by Django 4.0.5 on 2022-06-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
